
services:
    #PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        ports:
            - 8000:8000
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - mssql

    #Database Server
    mssql:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2017-latest
        restart: always
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${DB_PASSWORD}
        - MSSQL_PID=Developer
        ports:
        - 1433:1433
        volumes:
        - mssqlvolume:/var/opt/mssql
        - ./bk:/var/opt/mssql/backup

volumes:
    mssqlvolume:
